Update pr-checks.yml

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -35,6 +35,7 @@ jobs:
       - name: Create log file
         run: |
           touch error_log.txt
+          touch pass_log.txt
 
       - name: Check for naming conventions
         run: |
@@ -42,7 +43,9 @@ jobs:
 
           while IFS= read -r file; do
             if echo "$file" | grep -q " "; then
-              echo "The file or path $file contains spaces, please rename the path or file without spaces, using '_' instead." >> error_log.txt
+              echo "The file or path $file contains spaces, please rename the path or file without spaces, using underscore ('_') instead." >> error_log.txt
+            else
+              echo "Folders and files don't have spaces." >> pass_log.txt
             fi
 
             IFS='/' read -r -a fname_array <<< "$file";
@@ -50,28 +53,30 @@ jobs:
 
             if echo "${path}" | grep -qE '[A-Z]'; then
               echo "The path '$file' contains capital letters. Please write file paths in lower case." >> error_log.txt
+            else
+              echo "All folders and files are correctly named!" >> pass_log.txt
             fi
           done <<< "$all_files"
-          echo "All folders and files are correctly named!"
-
+    
       - name: Check for markdown file naming conventions
         run: |
           md_files=$(echo "${{ steps.changed_md_files.outputs.all_changed_files }}" | tr "," "\n")
           
           while IFS= read -r file; do
             md_fname=$(echo "$file" | tr "/" "\n" | grep "md" || true)  # Ensure grep doesn't exit
-            if ! echo "$md_fname" | grep -qE "^[^A-Z]+.md"; then
+            if echo $md_fname | grep -qE "^[^A-Z]+.md"; then
               echo "The markdown file $md_fname at path $file is not in all caps. Please write markdown file names using all caps." >> error_log.txt
+            else
+              echo "All markdown files are correctly named!" >> pass_log.txt
             fi
           done <<< "$md_files"
-          echo "All markdown files are correctly named!"
 
       - name: Check for PDF and Word files
         run: |
           echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr "," "\n" | if grep -q -e ".docx" -e ".pdf"; then
             echo "This PR contains PDF or word (.docx) files, please remove them and try again." >> error_log.txt
           else
-            echo "This PR does not contain PDF or word (.docx) files."
+            echo "This PR does not contain PDF or word (.docx) files." >> pass_log.txt
           fi
 
       - name: Setup Python 3.9
@@ -89,33 +94,32 @@ jobs:
           py_files=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr "," "\n" | grep ".py$" || true)
           if [ -n "$py_files" ]; then
             for file in $py_files; do
-              flake8 $file >> error_log.txt 2>&1
-              pylint $file --rcfile=ci_build/pylintrc >> error_log.txt 2>&1
-              # bandit -r $file >> error_log.txt 2>&1
+              flake8 $file
+              pylint $file --rcfile=ci_build/pylintrc
             done
           else
-            echo "No Python files to lint and check." >> error_log.txt
+            echo "No Python files to lint and check." >> pass_log.txt
           fi
 
-      # - name: Execute linting and security check on Jupyter Notebooks
-      #   run: |
-      #     nb_files=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr "," "\n" | grep ".ipynb$" || true)
-      #     if [ -n "$nb_files" ]; then
-      #       for file in $nb_files; do
-      #         nbqa flake8 $file >> error_log.txt 2>&1
-      #         nbqa pylint $file --rcfile=ci_build/pylintrc >> error_log.txt 2>&1
-      #         # nbqa bandit -r $file >> error_log.txt 2>&1
-      #       done
-      #     else
-      #       echo "No Jupyter Notebooks to lint." >> error_log.txt
-      #     fi
+      - name: Execute linting and security check on Jupyter Notebooks
+        run: |
+          nb_files=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr "," "\n" | grep ".ipynb$" || true)
+          if [ -n "$nb_files" ]; then
+            for file in $nb_files; do
+              nbqa flake8 $file
+              nbqa pylint $file --rcfile=ci_build/pylintrc
+            done
+          else
+            echo "No Jupyter Notebooks to lint." >> pass_log.txt
+          fi
 
-      - name: Display errors
+      - name: Display errors or pass
         run: |
           if [ -s error_log.txt ]; then
             echo "There were errors found:"
             cat error_log.txt
             exit 1
           else
-            echo "No errors found!"
+            cat pass_log.txt
+            # echo "No errors found!"
           fi
